# logspace 用于创建等比数列

In [2]:
import numpy as np
a = np.logspace(0,0,10)  # 创建一个等比数列，起始点是0，终止是0，总共10个数，但是幂是10
print(a)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [3]:
a = np.logspace(0,9,10)
print(a)

[  1.00000000e+00   1.00000000e+01   1.00000000e+02   1.00000000e+03
   1.00000000e+04   1.00000000e+05   1.00000000e+06   1.00000000e+07
   1.00000000e+08   1.00000000e+09]


## 如果想要改变基底,base = 2

In [4]:
a = np.logspace(0,9,10,base=2)
print(a)

[   1.    2.    4.    8.   16.   32.   64.  128.  256.  512.]


# 2 numpy.concatenate简单使用

###  numpy.concatenate((a1, a2, ...), axis=0, out=None)
### Parameters:	
### a1, a2, ... : sequence of array_like

#### The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).

### axis : int, optional ，The axis along which the arrays will be joined. Default is 0.

### out : ndarray, optional

#### If provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified.

#### Returns:	 res : ndarray



In [5]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)  # 这里的axis=0的表示按照行进行合并

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)  # 这里的axis=1的表示按照列进行合并

array([[1, 2, 5],
       [3, 4, 6]])